version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g "
    networks:
      - docker_elk
  elasticsearch2:
    build: elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Des.discovery.zen.ping.unicast.hosts=elasticsearch"
    networks:
      - docker_elk
  elasticsearch3:
    build: elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Des.discovery.zen.ping.unicast.hosts=elasticsearch"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/logs/:/var/log/logstash/
    networks:
      - docker_elk
  logstash2:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/logs/:/var/log/logstash/
    networks:
      - docker_elk
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - docker_elk
  filebeat:
    image: olinicola/filebeat:1.2.3
    volumes:
      - ./filebeat/config/filebeat.yml:/etc/filebeat/filebeat.yml
      - ./filebeat/logs:/var/log/
    networks:
      - docker_elk
networks:
  docker_elk:
    driver: bridge
